info:
  version: 1.0.0
  description: NWDAF initial local configuration

configuration:
  nwdafName: NWDAF
  sbi:
    scheme: http
    registerIPv4: 127.0.0.1 # IP used to register to NRF
    bindingIPv4: 127.0.0.1  # IP used to bind the service
    port: 29599
  serviceNameList:
    - nnwdaf-eventssubscription
    - nnwdaf-analyticsinfo
    # Operations:
    # - nnwdaf-eventssubscription-subscribe
    # - nnwdaf-eventssubscription-unsubscribe
    # - nnwdaf-eventssubscription-notify
    # - nnwdaf-analyticsinfo-request
  mongodb:
    name: free5gc
    url: mongodb://localhost:27017
  nrfUri: http://127.0.0.10:8000